name: Clon

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Download ngrok
      - name: Download ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      # Step 2: Extract ngrok
      - name: Extract
        run: Expand-Archive -Path ngrok.zip -DestinationPath .

      # Step 3: Authenticate ngrok
      - name: Auth
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      # Step 4: Enable RDP
      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      # Step 5: Save Installed Apps and Data Before Reset
      - name: Save Installed Apps & Data
        uses: actions/upload-artifact@v3
        with:
          name: rdp-session-data
          path: C:\Users\runneradmin\AppData\Local

      # Step 6: Start Ngrok Tunnel
      - name: Create Tunnel
        run: .\ngrok\ngrok.exe tcp 3389

      # Step 7: Automatically Stop Workflow After 5h 40m & Start New One
      - name: Auto Restart Workflow
        run: |
          Start-Sleep -Seconds 20400 # Wait 5 hours 40 minutes
          gh workflow run Clon.yml # Start new workflow before session expires
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # New Job: Restore Everything in New Workflow
  restore:
    runs-on: windows-latest
    needs: build

    steps:
      # Step 1: Restore Installed Apps & Data
      - name: Restore Installed Apps & Data
        uses: actions/download-artifact@v3
        with:
          name: rdp-session-data
          path: C:\Users\runneradmin\AppData\Local

      # Step 2: Re-Enable RDP and Ngrok
      - name: Re-Enable RDP
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      - name: Restart Ngrok Tunnel
        run: .\ngrok\ngrok.exe tcp 3389
