name: Auto Restart Ngrok

on:
  schedule:
    - cron: "49 */5 * * *"  # Runs every 5 hours and 49 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download Ngrok
        run: Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-windows-amd64.zip" -OutFile "ngrok.zip"
      
      - name: Extract Ngrok
        run: Expand-Archive -Path "ngrok.zip" -DestinationPath .

      - name: Authenticate Ngrok
        run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Stop Previous Ngrok Instance (if running)
        run: taskkill /IM ngrok.exe /F || echo "No previous instance found"

      - name: Start Ngrok Tunnel on the Same Port
        run: .\ngrok.exe tcp 3389  # Change to your preferred port

      - name: Keep the Workflow Alive
        run: Start-Sleep -Seconds 20940  # 5 hours 49 minutes (20940 seconds)
